import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Analysis Reports For Games By Day</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Analysis Reports For Games By Day</h1>

        <div className={styles.grid}>
          <a href="games" className={styles.card}>
            <h2>Best/Worst Games By Day &rarr;</h2>
            <p>Analyze best and worst days by loses/wins by day.</p>
          </a>

          <a href="gamesday" className={styles.card}>
            <h2>Games By Day of The Week &rarr;</h2>
            <p>Analyze wins and loses by day of the Week.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href="analysis">
          <a style={{color: 'white'}}>Back</a>
        </Link>
        <Link href="/">
          <a style={{color: 'white'}}>Home</a>
        </Link>
      </footer>
    </div>
  )
}
